# Generated by Django 4.2.1 on 2023-07-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cord', '0002_alter_post_options_post_sup_post_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sup_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_post', to='cord.post'),
        ),
    ]
